# Generated by Django 5.0.6 on 2024-06-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nutriment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutriment',
            old_name='user_id',
            new_name='user',
        ),
    ]
