# Generated by Django 5.0.6 on 2024-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nutriment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriment',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutriment',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutriment',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
